org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

flterraforged_version=0.1.0-SNAPSHOT
flterraforged_group=dev.foucaultleon

# Minecraft 1.20.1 reference binding
flterraforged_engine_version=0.1.0-SNAPSHOT
mc1201_minecraft_version=1.20.1
mc1201_yarn_mappings=1.20.1+build.10
mc1201_fabric_loader_version=0.19.5
