plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = 'flterraforged-engine-api'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'flterraforged-engine-api'
        }
    }
}
